# Rebuildable recipe, not a claim of bit-for-bit reproducible or tested container.
# Official source release fixes SQUID-2026:6/7/8/9; do not use older distro Squid.
FROM python:3.12.15-slim-bookworm@sha256:7753c33391fc9f01d1984375bf375eb6686d52ba10db6043a86634a5ccf90dcf AS build
RUN apt-get update && apt-get install -y --no-install-recommends build-essential perl pkg-config xz-utils \
    && rm -rf /var/lib/apt/lists/*
ADD --checksum=sha256:e3bd613b91b1c498ec2992276063342a85cd6edddd5521294e04f44bc055da9b https://github.com/squid-cache/squid/releases/download/SQUID_7_7/squid-7.7.tar.xz /tmp/squid.tar.xz
WORKDIR /tmp
RUN tar -xJf squid.tar.xz && cd squid-7.7 \
    && ./configure --prefix=/opt/squid --with-default-user=gateway \
       --disable-auth --disable-icap-client --disable-ecap --disable-htcp \
       --disable-icmp --disable-snmp --disable-wccp --disable-wccpv2 \
       --disable-cache-digests --disable-translation \
       --disable-external-acl-helpers --disable-url-rewrite-helpers \
       --without-openssl --without-gnutls --without-nettle \
    && make -j2 && make install \
    && dpkg-query -W -f='${Package}\t${Version}\n' > /opt/squid/build-packages.tsv

FROM python:3.12.15-slim-bookworm@sha256:7753c33391fc9f01d1984375bf375eb6686d52ba10db6043a86634a5ccf90dcf AS runtime
RUN apt-get update && apt-get install -y --no-install-recommends libstdc++6 libltdl7 libatomic1 \
    && rm -rf /var/lib/apt/lists/* \
    && groupadd --gid 10001 gateway \
    && useradd --uid 10001 --gid 10001 --create-home gateway
COPY --from=build /opt/squid /opt/squid
COPY deploy/egress/squid.conf /etc/squid/squid.conf
COPY deploy/egress/approved-hosts.txt /etc/squid/approved-hosts.txt
USER 10001:10001
RUN /opt/squid/sbin/squid -v && /opt/squid/sbin/squid -k parse -f /etc/squid/squid.conf
CMD ["/opt/squid/sbin/squid", "-N", "-f", "/etc/squid/squid.conf"]
